# Project
version=2.0.0
group=me.andreasmelone.glowingeyes
java_version=17

# Common
minecraft_version=1.19.4
mod_name=Glowing Eyes
mod_author=AndreasMelone
mod_id=glowingeyes
license=LGPL-3.0
credits=
description=Glowing Eyes is a Minecraft Mod to make your eyes glow, inspired by the Vampirism mod!
minecraft_version_range=[1.19.4]

common_runs_enabled=false
common_client_run_name=Common Client
common_server_run_name=Common Server

parchment_version=2023.06.26

# Forge
forge_loader_range=[43,)
forge_version=45.3.0
//forge_ats_enabled=true

# Fabric
fabric_version=0.77.0+1.19.4
fabric_loader_version=0.16.0

cca_version=5.1.0

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
