name: Trigger Build with Java 21

on:
  push:
    branches: [ "1.21.1", "1.21.4", "1.21.5", "1.21.6", "1.21.9" ]
  pull_request:
    branches: [ "1.21.1", "1.21.4", "1.21.5", "1.21.6", "1.21.9" ]

jobs:
  trigger:
    uses: RaydanOMGr/GlowingEyes/.github/workflows/build-j21.yml@workflows
    permissions:
      contents: write